# Generated by Django 5.1.3 on 2025-06-01 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique theme identifier (e.g., 'modern-minimal')",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Theme name must contain only lowercase letters, numbers, and hyphens.",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable theme name (e.g., 'Modern Minimal')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the theme's style and purpose",
                    ),
                ),
                (
                    "css_vars",
                    models.JSONField(
                        help_text="Complete CSS variables structure including theme, light, and dark modes"
                    ),
                ),
                (
                    "is_system_theme",
                    models.BooleanField(
                        default=False,
                        help_text="True for themes imported from JSON files, False for user-created themes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this theme is available for selection",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Theme version for tracking updates",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this theme (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="ThemeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_theme",
                    models.ForeignKey(
                        help_text="The currently active theme for the site",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_for_settings",
                        to="themes.theme",
                    ),
                ),
                (
                    "fallback_theme",
                    models.ForeignKey(
                        help_text="Fallback theme if current theme becomes unavailable",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fallback_for_settings",
                        to="themes.theme",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated the theme setting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme Setting",
                "verbose_name_plural": "Theme Settings",
            },
        ),
    ]
