# Generated by Django 5.1.3 on 2025-11-01 04:30

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', markdownx.models.MarkdownxField()),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary (auto-generated if empty)', max_length=300)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/featured/%Y/%m/')),
                ('og_image', models.ImageField(blank=True, help_text='Social share image (auto-uses featured if empty)', null=True, upload_to='blog/og/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (auto-uses title if empty)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for search engines', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if content published elsewhere first')),
                ('reading_time', models.IntegerField(default=1, help_text='Auto-calculated')),
                ('view_count', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('allow_comments', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'Post Metadata',
                'indexes': [models.Index(fields=['post', 'key'], name='blog_postme_post_id_abc583_idx')],
                'unique_together': {('post', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'publish_date'], name='blog_post_status_8279bd_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish_date'], name='blog_post_publish_7e8b08_idx'),
        ),
    ]
