# Generated by Django 5.1.3 on 2025-11-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.CharField(blank=True, default='', help_text='URL to featured image (upload or select from library)', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='og_image',
            field=models.CharField(blank=True, default='', help_text='URL to OG image (upload or select from library, auto-uses featured if empty)', max_length=500),
        ),
    ]
