# Generated by Django 5.1.3 on 2025-11-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_featured_image_alter_post_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='full_width_image',
            field=models.BooleanField(default=True, help_text='Display featured image at full width (vs constrained width)'),
        ),
    ]
