# Generated by Django 5.1.3 on 2025-11-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_full_width_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_background_opacity',
            field=models.FloatField(default=0.6, help_text='Background opacity (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='post',
            name='hero_background_type',
            field=models.CharField(blank=True, default='', help_text="Animated background type for hero section (e.g., 'clouds', 'waves', leave empty for none)", max_length=50),
        ),
    ]
