# Generated by Django 5.1.3 on 2025-11-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_hero_background_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_background_scope',
            field=models.CharField(choices=[('hero', 'Hero Section Only'), ('full', 'Full Page')], default='hero', help_text='Apply background to hero section only or entire page', max_length=20),
        ),
    ]
