# Generated by Django 5.1.3 on 2025-11-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_hero_background_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_background_size',
            field=models.CharField(choices=[('cover', 'Cover (stretch to fill)'), ('contain', 'Contain (fit without cropping)'), ('tile', 'Tile (repeat pattern)')], default='cover', help_text='How the background should scale and display', max_length=20),
        ),
    ]
