# Generated by Django 5.1.3 on 2025-11-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_hero_background_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_background_tile_size',
            field=models.IntegerField(default=100, help_text='Tile size as percentage of viewport height (10-200)'),
        ),
    ]
