# Generated by Django 5.1.3 on 2025-11-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_hero_background_tile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_background_tile_size',
            field=models.IntegerField(default=800, help_text='Tile size in pixels (100-2000)'),
        ),
    ]
