# Generated by Django 5.1.3 on 2025-11-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_hero_background_tile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword for SEO analysis', max_length=100),
        ),
    ]
