/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsrTestRouteImport } from './routes/ssr-test'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogNewRouteImport } from './routes/blog.new'
import { Route as BlogDashboardRouteImport } from './routes/blog.dashboard'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogTagSlugRouteImport } from './routes/blog.tag.$slug'
import { Route as BlogEditSlugRouteImport } from './routes/blog.edit.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'

const SsrTestRoute = SsrTestRouteImport.update({
  id: '/ssr-test',
  path: '/ssr-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNewRoute = BlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDashboardRoute = BlogDashboardRouteImport.update({
  id: '/blog/dashboard',
  path: '/blog/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/blog/tag/$slug',
  path: '/blog/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEditSlugRoute = BlogEditSlugRouteImport.update({
  id: '/blog/edit/$slug',
  path: '/blog/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/ssr-test': typeof SsrTestRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/dashboard': typeof BlogDashboardRoute
  '/blog/new': typeof BlogNewRoute
  '/blog': typeof BlogIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/edit/$slug': typeof BlogEditSlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/ssr-test': typeof SsrTestRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/dashboard': typeof BlogDashboardRoute
  '/blog/new': typeof BlogNewRoute
  '/blog': typeof BlogIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/edit/$slug': typeof BlogEditSlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/ssr-test': typeof SsrTestRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/dashboard': typeof BlogDashboardRoute
  '/blog/new': typeof BlogNewRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/edit/$slug': typeof BlogEditSlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/ssr-test'
    | '/blog/$slug'
    | '/blog/dashboard'
    | '/blog/new'
    | '/blog'
    | '/blog/category/$slug'
    | '/blog/edit/$slug'
    | '/blog/tag/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/ssr-test'
    | '/blog/$slug'
    | '/blog/dashboard'
    | '/blog/new'
    | '/blog'
    | '/blog/category/$slug'
    | '/blog/edit/$slug'
    | '/blog/tag/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/ssr-test'
    | '/blog/$slug'
    | '/blog/dashboard'
    | '/blog/new'
    | '/blog/'
    | '/blog/category/$slug'
    | '/blog/edit/$slug'
    | '/blog/tag/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  SsrTestRoute: typeof SsrTestRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogDashboardRoute: typeof BlogDashboardRoute
  BlogNewRoute: typeof BlogNewRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogEditSlugRoute: typeof BlogEditSlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ssr-test': {
      id: '/ssr-test'
      path: '/ssr-test'
      fullPath: '/ssr-test'
      preLoaderRoute: typeof SsrTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/new': {
      id: '/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof BlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/dashboard': {
      id: '/blog/dashboard'
      path: '/blog/dashboard'
      fullPath: '/blog/dashboard'
      preLoaderRoute: typeof BlogDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/blog/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/edit/$slug': {
      id: '/blog/edit/$slug'
      path: '/blog/edit/$slug'
      fullPath: '/blog/edit/$slug'
      preLoaderRoute: typeof BlogEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  SsrTestRoute: SsrTestRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogDashboardRoute: BlogDashboardRoute,
  BlogNewRoute: BlogNewRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogEditSlugRoute: BlogEditSlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
